services:
  - type: web
    name: vayusense-backend
    env: docker
    envVars:
      - key: GEE_PROJECT_ID
        sync: false
      - key: NASA_FIRMS_KEY
        sync: false
      - key: FRONTEND_PRODUCTION_URL
        value: https://vayusense.vercel.app
