import os
import ee
from utils.logger import setup_logger

logger = setup_logger("gee_auth")

def initialize_gee(service_account_path: str = None) -> bool:
    """
    Initializes Google Earth Engine.
    Checks for service account path, environmental variables, or default credentials.
    """
    try:
        if service_account_path and os.path.exists(service_account_path):
            logger.info(f"Attempting GEE initialization using Service Account JSON: {service_account_path}")
            credentials = ee.ServiceAccountCredentials('', service_account_path)
            ee.Initialize(credentials)
            logger.info("GEE successfully initialized using Service Account.")
            return True
            
        # Try checking environment variable
        env_sa_path = os.environ.get("EE_SERVICE_ACCOUNT_JSON")
        if env_sa_path and os.path.exists(env_sa_path):
            logger.info(f"Attempting GEE initialization using Env Service Account: {env_sa_path}")
            credentials = ee.ServiceAccountCredentials('', env_sa_path)
            ee.Initialize(credentials)
            logger.info("GEE successfully initialized using Env Service Account.")
            return True
            
        # Default initialization (looks for default credentials generated by 'ee.Authenticate()')
        logger.info("Attempting default GEE initialization...")
        ee.Initialize()
        logger.info("GEE successfully initialized with default credentials.")
        return True
        
    except Exception as e:
        logger.error(f"GEE Initialization failed: {e}")
        logger.info("Please run 'earthengine authenticate' in your command prompt to generate default credentials.")
        return False
